const express = require('express')
const mongoose = require('mongoose')
const routes = require('./routes/ToDoRoute')
const cors = require('cors')

require('dotenv').config()
const app = express()
app.use(express.json())
app.use(cors())
app.use(routes)
const PORT = process.env.PORT || 3001 
mongoose.connect(process.env.MONGODB_URL)
.then(()=>{console.log('MongoDB connected ...')})
.catch((err)=> console.log(err))
app.listen(PORT, ()=>{console.log(`Server is running on ${PORT}`)})